config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("dogs.urls", namespace='dogs')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dogs/urls.py
from django.urls import path
from .apps import DogsConfig
from . import views

app_name = DogsConfig.name

urlpatterns = [
    path("", views.index, name="index"),
    path("categories/", views.categories, name="categories"),
    path('<int:pk>/dogs', views.category_dogs, name='category_dogs')
]

dogs/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='Порода')
    description = models.TextField(null=True, blank=True, verbose_name='Описание')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'порода'
        verbose_name_plural = 'породы'


class Dog(models.Model):
    name = models.CharField(max_length=250, verbose_name='Кличка')
    # category = models.CharField(max_length=100, verbose_name='Порода')
    category = models.ForeignKey('Category', on_delete=models.CASCADE, verbose_name='Порода')

    phot = models.ImageField(upload_to='dogs/', null=True, blank=True, verbose_name='Фото')
    birth_day = models.DateField(null=True, blank=True, verbose_name='Дата рождения')

    def __str__(self):
        return f'{self.name} ({self.category})'

    class Meta:
        verbose_name = 'собака'
        verbose_name_plural = 'собаки'

dogs/views.py
from django.shortcuts import render
from .models import Category, Dog


# Create your views here.
def index(request):
    context = {
        'objects_list': Category.objects.all()[:3],
        'title': 'Питомник - Добро пожаловать'
    }

    return render(request, 'dogs/index.html', context)


def categories(request):
    context = {
        'objects_list': Category.objects.all(),
        'title': 'Питомник - Наши породы'
    }

    return render(request, 'dogs/categories.html', context)


def category_dogs(request, pk):
    category = Category.objects.get(pk=pk)
    context = {
        'objects_list': Dog.objects.filter(category_id=pk),
        'title': f'Все собаки породы {category.name}'
    }

    return render(request, 'dogs/dogs.html', context)

dogs/templates/dogs/base.html
{% load static %}
<!doctype html>
<html lang="en" data-bs-theme="auto">

<head>
    <script src="{% static 'js/color-modes.js'%}"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.115.4">
    <title>Питомник</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/album/">



    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">

    <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet">



    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

        .b-example-divider {
            width: 100%;
            height: 3rem;
            background-color: rgba(0, 0, 0, .1);
            border: solid rgba(0, 0, 0, .15);
            border-width: 1px 0;
            box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }

        .b-example-vr {
            flex-shrink: 0;
            width: 1.5rem;
            height: 100vh;
        }

        .bi {
            vertical-align: -.125em;
            fill: currentColor;
        }

        .nav-scroller {
            position: relative;
            z-index: 2;
            height: 2.75rem;
            overflow-y: hidden;
        }

        .nav-scroller .nav {
            display: flex;
            flex-wrap: nowrap;
            padding-bottom: 1rem;
            margin-top: -1px;
            overflow-x: auto;
            text-align: center;
            white-space: nowrap;
            -webkit-overflow-scrolling: touch;
        }

        .btn-bd-primary {
            --bd-violet-bg: #712cf9;
            --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

            --bs-btn-font-weight: 600;
            --bs-btn-color: var(--bs-white);
            --bs-btn-bg: var(--bd-violet-bg);
            --bs-btn-border-color: var(--bd-violet-bg);
            --bs-btn-hover-color: var(--bs-white);
            --bs-btn-hover-bg: #6528e0;
            --bs-btn-hover-border-color: #6528e0;
            --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
            --bs-btn-active-color: var(--bs-btn-hover-color);
            --bs-btn-active-bg: #5a23c8;
            --bs-btn-active-border-color: #5a23c8;
        }

        .bd-mode-toggle {
            z-index: 1500;
        }
    </style>


</head>

<body>
    <header data-bs-theme="dark">
        <div class="collapse text-bg-dark" id="navbarHeader">
            <div class="container">
              <div class="row">
                
                <div class="col-sm-4 offset-md-1 py-4">
                  <ul class="list-unstyled">
                    <li><a href="{% url 'dogs:index' %}" >Главная</a></li>
                    <li><a href="{% url 'dogs:categories' %}">Породы</a></li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <div class="navbar navbar-dark bg-dark shadow-sm">
            <div class="container">
              <a href="#" class="navbar-brand d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" viewBox="0 0 24 24"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
                <strong>Album</strong>
              </a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
            </div>
          </div>
      </header>
      

    <main>

        <section class="jumbotron text-center">
            <div class="container">
                <h1 class="jumbotron-heading">{{ title }}</h1>
            </div>
        </section>

        <div class="album py-5 bg-body-tertiary">
            <div class="container">
                {% block content %}
                
                {% endblock %}
            </div>
        </div>

    </main>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>

</html>

dogs/templates/dogs/categories.html
{% extends 'dogs/base.html' %}
{% block content %}
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    {% for object in objects_list %}
    {% include 'dogs/includes/inc-category.html' %}

    {% endfor %}
</div>
{% endblock %}

dogs/templates/dogs/dogs.html
{% extends 'dogs/base.html' %}
{% block content %}
{% for object in objects_list %}
{% load my_tags %}

<div class="col-4">
    <div class="card shadow-sm">
        <img class="card-img-top" src="{{ object.phot|my_media_filter }}" alt="Card image cap">
        <div class="card-body">
            <p class="card-text">{{object.name|title}}</p>
            <p class="card-text">{{object.description}}</p>

        </div>
    </div>
</div>
{% endfor %}

{% endblock %}

dogs/templates/dogs/includes/inc-category.html
<div class="col-4">
    <div class="card shadow-sm">
        
        <div class="card-body">
            <p class="card-text">{{object.name}}</p>
            <p class="card-text">{{object.description}}</p>
            <div class="btn-group">
                <a href="{% url 'dogs:category_dogs' object.pk %}" type="button" class="btn btn-sm btn-outline-secondary">К собакам</a>
            </div>

        </div>
    </div>
</div>

dogs/templates/dogs/index.html
{% extends 'dogs/base.html' %}
{% block content %}
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    {% for object in objects_list %}
    {% include 'dogs/includes/inc-category.html' %}
    {% endfor %}
</div>
{% endblock %}